spring.application.name=RECOMMENDATION-SERVICE
server.port=${RECOMMENDATION_SERVICE_PORT:8090}

eureka.client.service-url.defaultZone=${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.hostname=localhost
eureka.instance.ip-address=127.0.0.1
eureka.instance.prefer-ip-address=false
eureka.instance.instance-id=${spring.application.name}:${server.port}

management.endpoints.web.exposure.include=${RECOMMENDATION_ACTUATOR_EXPOSURE:*}

logging.level.org.springframework=INFO
